name = "Rocher Suchard"
author = "Adraug"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "738cd9de4e4327c1f952d95e2db683981ba8907afd6839a4973d5abc64c6b704"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
