name = "Rocher Suchard"
author = "Adraug"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0d314839c757b1e66d8cc853a686e6684d6b98d691681b011af3de7c4ab2af3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
