name = "Rocher Suchard"
author = "Adraug"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f856a534d67bb5cd68be9fbc2adb21b8eedc66c6128b711921e5888a5bc749b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
